### ISSUE TITLE
Request for functionality to filter by pageTypes

### ISSUE THREAD

**Issue by sandervsurksum** [vercel/speed-insights#58]
I believe it would be beneficial to add a functionality that allows me to filter the Kanban board by pageTypes within my Speed Insights.

Currently, I can filter the Kanban board based on routes and paths. However, for a more comprehensive analysis of performance, it would be highly beneficial to filter by pageTypes as well.

1. Page types provide valuable insights into how different sections of my application are performing in terms of speed, usability, and engagement.
2. By filtering the Kanban board based on pageTypes, I can gain deeper insights into the performance of specific page types, such as product detail pages, product listing pages, or checkout pages.
3. This functionality would enable us to focus my analysis and optimisation efforts on pages that are critical to our business objectives.
4. The page type information can be included in the "beforesend" parameter (https://vercel.com/docs/speed-insights/package#beforesend).

**Comment by feugy** [comment]
Hello.

While this is an interesting suggestion, we don't plan to address it in the near future, since we have many other feature we'd like to add (like attribution or data export).

There's a tricky challenge: How would a given page tag its metrics? Probably another React/Vue/Astro component, included in your page, to specify the applicable tags. This would need to be ironed out.
