### ISSUE TITLE
Bug in displaying results

### ISSUE THREAD

**Issue by sandervsurksum** [vercel/speed-insights#59]
There appears to be inconsistency in the display of scores on the metrics board in Speed Insights. Occasionally, the board for a specific metric, such as "Poor Scores," shows as empty, indicating "No poor scores." However, when clicking on "View All" button you will get a modal with routes or paths that have a poor score.

<img width="671" alt="Screenshot 2024-02-28 at 20 45 15" src="https://github.com/vercel/speed-insights/assets/122876560/5a4012d6-3cc1-49f8-ace9-4de8c173830b">

**Comment by timolins** [comment]
Hey @sandervsurksum,

This is intentional, note the little indicator line at the bottom.
![image](https://github.com/vercel/speed-insights/assets/2978876/757e6761-ca3e-478b-869b-64b31f6143f5)

Pages with relatively little traffic (below 0.5% of total traffic) get hidden in the main panel, to keep the them focused and less noisy.

Hope that helps!
